//! `project_map` — the structural overview a codebase-understanding task
//! should start from, instead of reading every file.
//!
//! # Why this exists
//!
//! Orienting in an unfamiliar repo used to cost a `list_dir` per directory
//! (non-recursive) plus a whole-file `read_file` per file, because there was
//! no way to learn what a file *contains* without reading all of it. On this
//! very repo that's ~20 directory calls and ~108k tokens of file content —
//! more than a 128k context window has to spare before the model has written
//! a word, and re-sent on every subsequent turn.
//!
//! One call here returns the tree plus each file's top-level definitions with
//! line numbers, for a small fraction of that. The intended workflow is
//! **map, then read precisely**: outline the repo, then `read_file` only the
//! handful of files that actually matter.
//!
//! # Why a line scanner and not tree-sitter
//!
//! Real parsers (grok-build uses tree-sitter with per-language query
//! grammars) give exact symbol extraction and go-to-definition. They also
//! mean a C grammar crate per language — and this binary cross-compiles to
//! five platform targets, where a C toolchain per target is a real ongoing
//! cost for what is, here, a *navigation hint*.
//!
//! So this scans lines with per-language rules. The tradeoff is explicit: it
//! can miss an unusually-formatted definition, and it will never see symbols
//! generated by macros. It fails in the harmless direction — a missed symbol
//! is simply absent, never a wrong file path or a build break — and every
//! line number it prints is real, because it comes from counting actual
//! lines rather than inferring position.

use std::collections::BTreeMap;
use std::path::Path;

use async_trait::async_trait;
use serde::Deserialize;
use serde_json::value::RawValue;

use crate::error::ToolError;
use crate::fs::Workspace;
use crate::tool::{Tool, obj_schema};
use crate::walk::walk_files;

/// Files scanned before the map stops growing. Well past any repo where a
/// single map call is the right move; past this the model should scope to a
/// subdirectory with `path`.
const MAX_FILES: usize = 600;
/// Per-file symbol ceiling — one 5000-line generated file must not crowd out
/// every other file in the map.
const MAX_SYMBOLS_PER_FILE: usize = 40;
/// Signatures are truncated to this; enough for a name plus argument shape.
const MAX_SIGNATURE_CHARS: usize = 110;
/// Hard ceiling on the whole result. This tool exists to *save* context, so
/// it must never be the thing that floods it. Matches `read_file`'s cap.
const MAX_OUTPUT_CHARS: usize = 60_000;
/// Source indentation is echoed (so methods visibly nest under their type)
/// but clamped — deeply nested code shouldn't push signatures off the right.
const MAX_INDENT: usize = 6;

/// Keywords that introduce a definition, per language family.
struct Rules {
    /// Matched after leading modifiers are stripped.
    keywords: &'static [&'static str],
    /// Line prefixes that mean "this is a comment, not code".
    comments: &'static [&'static str],
    /// Treat `const name = (…) => {}` as a definition. An explicit flag
    /// rather than comparing `rules` against the JS table by address:
    /// `const` items are inlined at every use site, so two `&JSTS`
    /// expressions are not guaranteed to share an address and a
    /// `ptr::eq` check silently never fires.
    arrow_fn_assignments: bool,
    /// Recognize keyword-less class methods (`handleClick(e) {`). Needed
    /// for JS/TS/Java/C#/Swift, where methods have no introducing keyword
    /// at all -- without it those outlines list every class and none of
    /// their contents, which is most of what a reader wants. Off for
    /// Rust/Python/Go, whose methods already start with `fn`/`def`/`func`.
    keywordless_methods: bool,
}

/// Words that look like a method call site but are control flow.
const CONTROL_KEYWORDS: &[&str] = &[
    "if", "for", "while", "switch", "catch", "return", "do", "else", "with", "try", "using",
    "when", "match", "await", "yield", "throw", "new", "case",
];

/// Is `rest` a keyword-less method definition, e.g. `handleClick(e) {`,
/// `get inputDisabled(): boolean {`, `public void doThing() {`?
///
/// Structural rather than keyword-based: an identifier immediately followed
/// by an argument list, on a line that opens a body. Requiring the trailing
/// `{` is what keeps ordinary call sites (`doSomething();`) out.
fn looks_like_method(rest: &str) -> bool {
    if !rest.trim_end().ends_with('{') {
        return false;
    }
    let Some(paren) = rest.find('(') else {
        return false;
    };
    let before = &rest[..paren];
    let mut tokens = before.split_whitespace().collect::<Vec<_>>();
    let Some(name) = tokens.pop() else {
        return false;
    };
    // `[modifiers] [return type] name(` -- more words than that and this is
    // some other construct we shouldn't guess at.
    if tokens.len() > 2 {
        return false;
    }
    if CONTROL_KEYWORDS.contains(&name) {
        return false;
    }
    let mut chars = name.chars();
    let first_ok = chars
        .next()
        .is_some_and(|c| c.is_alphabetic() || c == '_' || c == '$');
    first_ok && chars.all(|c| c.is_alphanumeric() || c == '_' || c == '$')
}

/// Modifiers to strip before keyword matching, so `pub async fn foo` and
/// `export default class Bar` both reduce to their defining keyword.
const MODIFIERS: &[&str] = &[
    "pub",
    "export",
    "default",
    "async",
    "public",
    "private",
    "protected",
    "internal",
    "final",
    "abstract",
    "override",
    "open",
    "suspend",
    "static",
    "extern",
    "unsafe",
    "inline",
    "virtual",
    "declare",
    "readonly",
];

const RUST: Rules = Rules {
    keywords: &[
        "fn",
        "struct",
        "enum",
        "trait",
        "impl",
        "type",
        "const",
        "mod",
        "union",
        "macro_rules!",
    ],
    comments: &["//", "/*", "*"],
    arrow_fn_assignments: false,
    keywordless_methods: false,
};

const PYTHON: Rules = Rules {
    keywords: &["def", "class"],
    comments: &["#"],
    arrow_fn_assignments: false,
    keywordless_methods: false,
};

/// JS/TS deliberately omits bare `const`/`let`/`var`: listing every constant
/// buries the actual structure. Arrow-function assignments are recovered
/// separately in `is_definition`, which is the case that genuinely matters.
const JSTS: Rules = Rules {
    keywords: &[
        "function",
        "class",
        "interface",
        "type",
        "enum",
        "namespace",
    ],
    comments: &["//", "/*", "*"],
    arrow_fn_assignments: true,
    keywordless_methods: true,
};

const GO: Rules = Rules {
    keywords: &["func", "type", "package"],
    comments: &["//", "/*", "*"],
    arrow_fn_assignments: false,
    keywordless_methods: false,
};

/// Everything else: the keywords shared across C-family, JVM, Ruby, PHP and
/// friends. Broad on purpose — a few extra lines beat a blank outline.
const GENERIC: Rules = Rules {
    keywords: &[
        "class",
        "struct",
        "interface",
        "enum",
        "def",
        "func",
        "function",
        "fn",
        "module",
        "trait",
        "record",
        "object",
        "protocol",
        "impl",
        "namespace",
        "type",
        "#define",
    ],
    comments: &["//", "/*", "*", "#", "--", ";"],
    arrow_fn_assignments: false,
    keywordless_methods: true,
};

fn rules_for(extension: &str) -> Option<&'static Rules> {
    match extension {
        "rs" => Some(&RUST),
        "py" | "pyi" => Some(&PYTHON),
        "js" | "jsx" | "mjs" | "cjs" | "ts" | "tsx" | "mts" | "cts" => Some(&JSTS),
        "go" => Some(&GO),
        "java" | "kt" | "kts" | "scala" | "swift" | "c" | "h" | "cc" | "cpp" | "hpp" | "cs"
        | "rb" | "php" | "dart" | "ex" | "exs" | "lua" | "zig" | "sh" | "bash" => Some(&GENERIC),
        // Not a source file we know how to outline (json, md, toml, ...).
        // Still listed in the tree with its line count -- knowing a file
        // exists is useful even when its contents aren't symbol-shaped.
        _ => None,
    }
}

/// Does this line open a definition? Returns the cleaned-up signature.
fn is_definition(line: &str, rules: &Rules) -> Option<String> {
    let trimmed = line.trim();
    if trimmed.is_empty() {
        return None;
    }
    if rules.comments.iter().any(|c| trimmed.starts_with(c)) {
        return None;
    }

    // Strip modifiers one at a time: `pub async fn` -> `async fn` -> `fn`.
    // `pub(crate)` and friends are handled by matching on the prefix.
    let mut rest = trimmed;
    loop {
        let head = rest.split_whitespace().next().unwrap_or("");
        let bare = head.split('(').next().unwrap_or(head); // pub(crate) -> pub
        if MODIFIERS.contains(&bare) && head != "type" {
            rest = rest[head.len()..].trim_start();
            if rest.is_empty() {
                return None;
            }
            continue;
        }
        break;
    }

    let head = rest.split_whitespace().next().unwrap_or("");
    let matched = rules.keywords.contains(&head)
        // `macro_rules!` / `#define` carry punctuation, so compare by prefix.
        || rules
            .keywords
            .iter()
            .any(|k| k.ends_with('!') && head.starts_with(k));

    // JS/TS arrow functions: `const handler = (a) => {`. Only counted when
    // the value really is a function, so plain constants stay out.
    let arrow_fn = !matched
        && rules.arrow_fn_assignments
        && matches!(head, "const" | "let" | "var")
        && (rest.contains("=>") || rest.contains("function"));

    let method = !matched && !arrow_fn && rules.keywordless_methods && looks_like_method(rest);

    if !matched && !arrow_fn && !method {
        return None;
    }

    Some(clean_signature(trimmed))
}

/// Trim a definition line down to its signature: drop the opening brace and
/// any trailing noise, and bound the length.
fn clean_signature(line: &str) -> String {
    let cut = line
        .find(" {")
        .or_else(|| line.strip_suffix('{').map(|s| s.len()))
        .unwrap_or(line.len());
    let sig = line[..cut]
        .trim_end()
        .trim_end_matches(&[',', ';'][..])
        .trim();
    if sig.chars().count() <= MAX_SIGNATURE_CHARS {
        return sig.to_string();
    }
    let head: String = sig.chars().take(MAX_SIGNATURE_CHARS).collect();
    format!("{head}…")
}

/// Leading-whitespace width, tabs counted as 4, clamped for display.
fn indent_of(line: &str) -> usize {
    let width: usize = line
        .chars()
        .take_while(|c| c.is_whitespace())
        .map(|c| if c == '\t' { 4 } else { 1 })
        .sum();
    width.min(MAX_INDENT)
}

struct FileOutline {
    /// Workspace-relative path.
    rel: String,
    lines: usize,
    /// `(line number, indent, signature)`.
    symbols: Vec<(usize, usize, String)>,
    truncated: bool,
}

fn outline_file(path: &Path, rel: String) -> Option<FileOutline> {
    let contents = std::fs::read_to_string(path).ok()?; // binary/unreadable
    let lines = contents.lines().count();
    let extension = path
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("")
        .to_ascii_lowercase();

    let Some(rules) = rules_for(&extension) else {
        return Some(FileOutline {
            rel,
            lines,
            symbols: Vec::new(),
            truncated: false,
        });
    };

    let mut symbols = Vec::new();
    let mut truncated = false;
    for (i, line) in contents.lines().enumerate() {
        if let Some(sig) = is_definition(line, rules) {
            if symbols.len() >= MAX_SYMBOLS_PER_FILE {
                truncated = true;
                break;
            }
            symbols.push((i + 1, indent_of(line), sig));
        }
    }

    Some(FileOutline {
        rel,
        lines,
        symbols,
        truncated,
    })
}

#[derive(Deserialize)]
struct MapArgs {
    #[serde(default)]
    path: Option<String>,
}

/// Recursive structural map of the workspace: tree plus per-file symbols.
pub struct ProjectMap(pub Workspace);

#[async_trait]
impl Tool for ProjectMap {
    fn name(&self) -> &str {
        "project_map"
    }
    fn description(&self) -> &str {
        "Get a structural map of the codebase in ONE call: the recursive file tree plus each \
         file's top-level definitions (functions, classes, structs, types) with line numbers. \
         Start here to understand an unfamiliar codebase or locate where something lives -- it \
         is far cheaper than listing directories one by one and reading whole files, and the \
         line numbers tell you exactly which files and regions are worth reading next. Pass \
         `path` to map a subdirectory. Read-only, no approval needed."
    }
    fn schema(&self) -> serde_json::Value {
        obj_schema(
            &[(
                "path",
                serde_json::json!({
                    "type": "string",
                    "description": "optional workspace-relative directory to map (default: the whole workspace)"
                }),
            )],
            &[],
        )
    }

    async fn execute(&self, args: &RawValue) -> Result<String, ToolError> {
        let a: MapArgs = serde_json::from_str(args.get())?;
        let requested = a
            .path
            .filter(|p| !p.is_empty())
            .unwrap_or_else(|| ".".into());
        let root = self.0.resolve(&requested)?;
        // Distinguish "this directory doesn't exist" from "this directory
        // has nothing worth mapping" -- reporting the latter for a typo'd
        // path sends the model looking for a content problem that isn't
        // there.
        if !root.is_dir() {
            return Err(ToolError::Message(format!(
                "{requested}: not a directory (use list_dir to see what's there)"
            )));
        }
        let strip_base = self.0.resolve(".")?;

        // Reading and scanning files is blocking CPU/IO work; keep it off
        // the reactor.
        let output = tokio::task::spawn_blocking(move || {
            let mut files: Vec<FileOutline> = Vec::new();
            let mut scanned = 0usize;
            let mut hit_file_cap = false;

            for path in walk_files(&root) {
                if scanned >= MAX_FILES {
                    hit_file_cap = true;
                    break;
                }
                let rel = path
                    .strip_prefix(&strip_base)
                    .unwrap_or(&path)
                    .display()
                    .to_string();
                if let Some(outline) = outline_file(&path, rel) {
                    files.push(outline);
                    scanned += 1;
                }
            }

            files.sort_by(|a, b| a.rel.cmp(&b.rel));
            render(&files, hit_file_cap)
        })
        .await
        .map_err(|e| ToolError::Message(format!("project_map task failed: {e}")))?;

        Ok(output)
    }
}

/// Group by directory and render. Deterministic ordering throughout: the
/// same workspace must map identically twice running, or it would break the
/// prompt-prefix cache the rest of the system is careful to preserve.
fn render(files: &[FileOutline], hit_file_cap: bool) -> String {
    if files.is_empty() {
        return "(no files found — check the path, or the directory may contain only ignored/build output)".to_string();
    }

    let mut by_dir: BTreeMap<&str, Vec<&FileOutline>> = BTreeMap::new();
    for f in files {
        let dir = match f.rel.rfind('/') {
            Some(i) => &f.rel[..i],
            None => ".",
        };
        by_dir.entry(dir).or_default().push(f);
    }

    let total_symbols: usize = files.iter().map(|f| f.symbols.len()).sum();
    let mut out = format!("{} files, {} definitions\n", files.len(), total_symbols);

    let mut truncated_output = false;
    'dirs: for (dir, group) in &by_dir {
        out.push_str(&format!("\n{dir}/\n"));
        for f in group {
            let name = f.rel.rsplit('/').next().unwrap_or(&f.rel);
            out.push_str(&format!("  {name}  ({} lines)\n", f.lines));
            for (line_no, indent, sig) in &f.symbols {
                out.push_str(&format!(
                    "    {line_no:>5}  {:indent$}{sig}\n",
                    "",
                    indent = indent
                ));
            }
            if f.truncated {
                out.push_str(&format!(
                    "           … more than {MAX_SYMBOLS_PER_FILE} definitions; read the file for the rest\n"
                ));
            }
            if out.len() >= MAX_OUTPUT_CHARS {
                truncated_output = true;
                break 'dirs;
            }
        }
    }

    if truncated_output {
        out.push_str(
            "\n[map truncated to stay within context — pass `path` to map one subdirectory at a time]\n",
        );
    } else if hit_file_cap {
        out.push_str(&format!(
            "\n[stopped after {MAX_FILES} files — pass `path` to map a subdirectory]\n"
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ws(name: &str) -> Workspace {
        let dir = std::env::temp_dir().join(format!("hivemind_map_test_{name}"));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        Workspace::new(dir)
    }

    fn args(json: serde_json::Value) -> Box<RawValue> {
        RawValue::from_string(json.to_string()).unwrap()
    }

    // -- language rules -----------------------------------------------------

    #[test]
    fn rust_definitions_are_recognized_through_their_modifiers() {
        for line in [
            "fn plain()",
            "pub fn exported()",
            "pub async fn streamed()",
            "pub(crate) fn scoped()",
            "    pub async fn indented_method(&mut self)",
            "struct Thing {",
            "pub enum Kind {",
            "impl Tool for ProjectMap {",
            "pub trait Ui: Send + Sync {",
            "macro_rules! thing {",
        ] {
            assert!(
                is_definition(line, &RUST).is_some(),
                "should have matched: {line}"
            );
        }
    }

    #[test]
    fn rust_non_definitions_are_ignored() {
        for line in [
            "// fn commented_out()",
            "/// doc comment mentioning fn",
            "let x = call_fn();",
            "    self.fn_like_field = 1;",
            "",
            "        // pub fn nope()",
        ] {
            assert!(
                is_definition(line, &RUST).is_none(),
                "should NOT have matched: {line}"
            );
        }
    }

    #[test]
    fn python_and_go_and_js_each_match_their_own_shapes() {
        assert!(is_definition("def handler(request):", &PYTHON).is_some());
        assert!(is_definition("class Model:", &PYTHON).is_some());
        assert!(is_definition("# def commented", &PYTHON).is_none());

        assert!(is_definition("func Serve(w http.ResponseWriter)", &GO).is_some());
        assert!(is_definition("type Config struct {", &GO).is_some());

        assert!(is_definition("export function render() {", &JSTS).is_some());
        assert!(is_definition("export default class App {", &JSTS).is_some());
        assert!(is_definition("interface Props {", &JSTS).is_some());
    }

    #[test]
    fn js_arrow_functions_count_but_plain_constants_do_not() {
        // The distinction that keeps a JS outline readable: every module has
        // dozens of constants and only a few of them are functions.
        assert!(is_definition("const handler = (req) => {", &JSTS).is_some());
        assert!(is_definition("const run = async () => {", &JSTS).is_some());
        assert!(is_definition("const doIt = function () {", &JSTS).is_some());
        assert!(is_definition("const MAX_RETRIES = 5;", &JSTS).is_none());
        assert!(is_definition("let counter = 0;", &JSTS).is_none());
    }

    #[test]
    fn keywordless_class_methods_are_found() {
        // TS/Java/C#/Swift methods have no introducing keyword -- without
        // this the outline lists every class and none of its contents.
        for line in [
            "  handleClick(event) {",
            "  get inputDisabled(): boolean {",
            "  async sendUserMessage(text: string): void {",
            "  public void doThing() {",
            "  constructor(private readonly x: Y) {",
        ] {
            assert!(
                is_definition(line, &JSTS).is_some(),
                "should have matched: {line}"
            );
        }
    }

    #[test]
    fn control_flow_and_call_sites_are_not_mistaken_for_methods() {
        // The false positives that would otherwise flood a JS/TS outline.
        for line in [
            "  if (ready) {",
            "  for (const x of items) {",
            "  while (true) {",
            "  } catch (err) {",
            "  switch (kind) {",
            "  doSomething();",
            "  const total = add(1) + add(2);",
            "  return compute(x);",
            "  }).then((r) => {",
        ] {
            assert!(
                is_definition(line, &JSTS).is_none(),
                "should NOT have matched: {line}"
            );
        }
    }

    #[test]
    fn rust_does_not_use_the_keywordless_method_heuristic() {
        // Rust methods all start with `fn`, so the looser rule would only
        // add noise (e.g. `match x {`).
        assert!(is_definition("    match value {", &RUST).is_none());
        assert!(is_definition("    if let Some(x) = y {", &RUST).is_none());
    }

    #[test]
    fn signatures_drop_the_opening_brace_and_are_length_bounded() {
        assert_eq!(
            is_definition("pub fn run(&mut self) -> Result<()> {", &RUST).unwrap(),
            "pub fn run(&mut self) -> Result<()>"
        );
        let long = format!("pub fn x({}) {{", "arg: SomeVeryLongTypeName, ".repeat(20));
        let sig = is_definition(&long, &RUST).unwrap();
        assert!(sig.chars().count() <= MAX_SIGNATURE_CHARS + 1, "{sig}");
        assert!(sig.ends_with('…'));
    }

    // -- end to end ---------------------------------------------------------

    #[tokio::test]
    async fn maps_a_tree_with_real_line_numbers() {
        let w = ws("e2e");
        std::fs::create_dir_all(w.root.join("src")).unwrap();
        std::fs::write(
            w.root.join("src/lib.rs"),
            "// header\n\npub struct Engine {\n    field: u8,\n}\n\nimpl Engine {\n    pub fn start(&self) {}\n}\n",
        )
        .unwrap();
        std::fs::write(w.root.join("README.md"), "# docs\nsome prose\n").unwrap();

        let out = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({})))
            .await
            .unwrap();

        assert!(out.contains("lib.rs"), "{out}");
        assert!(out.contains("pub struct Engine"), "{out}");
        assert!(out.contains("impl Engine"), "{out}");
        assert!(out.contains("pub fn start"), "{out}");
        // Line numbers must be real: `pub struct Engine` is on line 3.
        assert!(
            out.lines()
                .any(|l| l.contains("3") && l.contains("pub struct Engine")),
            "expected a real line number for the struct:\n{out}"
        );
        // Non-source files still appear, so the model knows they exist.
        assert!(out.contains("README.md"), "{out}");
    }

    #[tokio::test]
    async fn can_be_scoped_to_a_subdirectory() {
        let w = ws("scoped");
        std::fs::create_dir_all(w.root.join("src")).unwrap();
        std::fs::create_dir_all(w.root.join("vendor")).unwrap();
        std::fs::write(w.root.join("src/a.rs"), "pub fn wanted() {}\n").unwrap();
        std::fs::write(w.root.join("vendor/b.rs"), "pub fn unwanted() {}\n").unwrap();

        let out = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({"path": "src"})))
            .await
            .unwrap();
        assert!(out.contains("wanted"), "{out}");
        assert!(!out.contains("unwanted"), "scope leaked:\n{out}");
    }

    #[tokio::test]
    async fn build_output_and_vcs_are_excluded_by_the_shared_walk_policy() {
        // Same IGNORED_DIRS every other read-only tool uses, so "the
        // codebase" means one thing across the toolset.
        let w = ws("ignored");
        std::fs::create_dir_all(w.root.join("node_modules")).unwrap();
        std::fs::create_dir_all(w.root.join("target")).unwrap();
        std::fs::write(w.root.join("node_modules/dep.js"), "function dep() {}\n").unwrap();
        std::fs::write(w.root.join("target/gen.rs"), "pub fn generated() {}\n").unwrap();
        std::fs::write(w.root.join("main.rs"), "pub fn real() {}\n").unwrap();

        let out = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({})))
            .await
            .unwrap();
        assert!(out.contains("real"), "{out}");
        assert!(!out.contains("dep"), "node_modules leaked:\n{out}");
        assert!(!out.contains("generated"), "target/ leaked:\n{out}");
    }

    #[tokio::test]
    async fn a_file_with_too_many_definitions_is_capped_not_dropped() {
        let w = ws("symbol_cap");
        let body: String = (0..MAX_SYMBOLS_PER_FILE + 25)
            .map(|i| format!("pub fn f{i}() {{}}\n"))
            .collect();
        std::fs::write(w.root.join("many.rs"), body).unwrap();

        let out = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({})))
            .await
            .unwrap();
        assert!(out.contains("many.rs"));
        assert!(out.contains("more than"), "expected a cap notice:\n{out}");
        assert!(!out.contains("f60"), "cap was not enforced:\n{out}");
    }

    #[tokio::test]
    async fn output_is_bounded_even_for_a_large_workspace() {
        // The tool exists to save context; it must never be what floods it.
        let w = ws("output_cap");
        for i in 0..300 {
            let body: String = (0..30)
                .map(|j| format!("pub fn f{i}_{j}() {{}}\n"))
                .collect();
            std::fs::write(w.root.join(format!("f{i}.rs")), body).unwrap();
        }
        let out = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({})))
            .await
            .unwrap();
        assert!(
            out.len() <= MAX_OUTPUT_CHARS + 500,
            "output was {} chars",
            out.len()
        );
        assert!(out.contains("truncated"), "should say it was cut:\n{out}");
    }

    #[tokio::test]
    async fn a_nonexistent_path_says_so_instead_of_reporting_an_empty_map() {
        // "no files found" for a typo'd path sends the model hunting for a
        // content problem that doesn't exist.
        // A path whose parent exists but whose leaf does not -- exactly the
        // `src/crates` typo shape. (A path whose *parent* is also missing
        // is rejected earlier, by Workspace::resolve.)
        let w = ws("missing_dir");
        let err = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({"path": "nope"})))
            .await
            .unwrap_err();
        assert!(err.to_string().contains("not a directory"), "{err}");

        // Pointing it at a file rather than a directory is the same class
        // of mistake and gets the same clear answer.
        std::fs::write(w.root.join("a.rs"), "pub fn x() {}\n").unwrap();
        let err = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({"path": "a.rs"})))
            .await
            .unwrap_err();
        assert!(err.to_string().contains("not a directory"), "{err}");
    }

    #[tokio::test]
    async fn an_empty_directory_reports_cleanly() {
        let w = ws("empty");
        let out = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({})))
            .await
            .unwrap();
        assert!(out.contains("no files found"), "{out}");
    }

    #[tokio::test]
    async fn escaping_the_workspace_is_refused() {
        let w = ws("escape");
        let err = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({"path": "../.."})))
            .await
            .unwrap_err();
        assert!(
            err.to_string().to_lowercase().contains("workspace"),
            "{err}"
        );
    }

    #[tokio::test]
    async fn binary_files_are_skipped_without_failing_the_map() {
        let w = ws("binary");
        std::fs::write(w.root.join("blob.bin"), [0xff, 0xfe, 0x00, 0x01]).unwrap();
        std::fs::write(w.root.join("ok.rs"), "pub fn fine() {}\n").unwrap();
        let out = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({})))
            .await
            .unwrap();
        assert!(
            out.contains("fine"),
            "a bad file must not break the map:\n{out}"
        );
    }

    #[tokio::test]
    async fn the_same_workspace_maps_identically_twice() {
        // Stable output keeps the prompt prefix cacheable across turns.
        let w = ws("determinism");
        std::fs::create_dir_all(w.root.join("a")).unwrap();
        std::fs::create_dir_all(w.root.join("b")).unwrap();
        std::fs::write(w.root.join("a/one.rs"), "pub fn one() {}\n").unwrap();
        std::fs::write(w.root.join("b/two.rs"), "pub fn two() {}\n").unwrap();

        let first = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({})))
            .await
            .unwrap();
        let second = ProjectMap(w.clone())
            .execute(&args(serde_json::json!({})))
            .await
            .unwrap();
        assert_eq!(first, second);
    }
}
